### ISSUE TITLE
添加了QChatAIPaint插件后主程序无法启动

### ISSUE THREAD

**Issue by xanthichi** [oliverkirk-sudo/QChatWeather#2]
在跑起来之后通过机器人命令安装了QChatAIPaint插件，然后！reload后台日志机器人报错但未停止响应，但是与之对话无反应。配置好插件的config并安装了插件所需的pydantic==1.8.2之后主程序启动就报错
日志信息
Traceback (most recent call last):
File "/root/QChatGPT/main.py", line 57, in
from pkg.utils.log import init_runtime_log_file, reset_logging
File "/root/QChatGPT/pkg/utils/log.py", line 6, in
from . import context
File "/root/QChatGPT/pkg/utils/context.py", line 7, in
from ..openai import manager as openai_mgr
File "/root/QChatGPT/pkg/openai/manager.py", line 3, in
import openai
File "/usr/local/lib/python3.10/dist-packages/openai/init.py", line 8, in
from . import types
File "/usr/local/lib/python3.10/dist-packages/openai/types/init.py", line 5, in
from .edit import Edit as Edit
File "/usr/local/lib/python3.10/dist-packages/openai/types/edit.py", line 6, in
from .._models import BaseModel
File "/usr/local/lib/python3.10/dist-packages/openai/_models.py", line 33, in
from ._utils import (
File "/usr/local/lib/python3.10/dist-packages/openai/_utils/init.py", line 2, in
from ._utils import flatten as flatten
File "/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py", line 24, in
from .._compat import parse_date as parse_date
File "/usr/local/lib/python3.10/dist-packages/openai/_compat.py", line 55, in
from pydantic.typing import is_union as is_union
ImportError: cannot import name 'is_union' from 'pydantic.typing' (/usr/local/lib/python3.10/dist-packages/pydantic/typing.py)

启用的插件
QChatAIPaint
WebwlkrPlugin

**Comment by oliverkirk-sudo** [comment]
[QChatAIPaint](https://github.com/oliverkirk-sudo/QChatAIPaint)的仓库在这，且QChatAIPaint不需要pydantic

**Comment by huxiaotao0620** [comment]
我的也一样启动不了了

**Comment by oliverkirk-sudo** [comment]
把pydantic升级到最新版试试
