### ISSUE TITLE
添加本插件后无法启动

### ISSUE THREAD

**Issue by bobandbrony** [oliverkirk-sudo/QChatWeather#3]
Traceback (most recent call last):
  File "D:\chatbot\4494-\QChatGPT-3.2.0.1\main.py", line 72, in <module>
    asyncio.run(main_entry())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\chatbot\4494-\QChatGPT-3.2.0.1\main.py", line 25, in main_entry
    missing_deps = await deps.check_deps()
  File "D:\chatbot\4494-\QChatGPT-3.2.0.1\pkg\core\bootutils\deps.py", line 27, in check_deps
    __import__(dep)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\__init__.py", line 22, in <module>
    from mirai.bot import (
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\bot.py", line 13, in <module>
    import mirai.models.api
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\models\__init__.py", line 10, in <module>
    from mirai.models.bus import ModelEventBus
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\models\bus.py", line 12, in <module>
    from mirai.models.events import Event
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\models\events.py", line 17, in <module>
    from mirai.models.base import MiraiIndexedModel
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\models\base.py", line 11, in <module>
    class MiraiMetaclass(pdm.ModelMetaclass):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic\_migration.py", line 306, in wrapper
    raise AttributeError(f'module {module!r} has no attribute {name!r}')
AttributeError: module 'pydantic.main' has no attribute 'ModelMetaclass'

**Comment by oliverkirk-sudo** [comment]
pydantic版本有问题，用别的版本

**Comment by bobandbrony** [comment]
> pydantic版本有问题，用别的版本

那用哪个版本呢
目前用的是最新版，qchat的requirements.txt是这样写的，还有就是qchat已经不支持py3.9了

**Comment by oliverkirk-sudo** [comment]
这个是[YiriMirai](https://github.com/YiriMiraiProject/YiriMirai)的问题，不过这个项目好像没更新了，原本消息发送是依赖这个库的

**Comment by bobandbrony** [comment]
> 这个是[YiriMirai](https://github.com/YiriMiraiProject/YiriMirai)的问题，不过这个项目好像没更新了，原本消息发送是依赖这个库的

啊，那就没解决方案了吗。。。
